spring:
  application:
    name: cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config"
  security:
    user:
      name: admin
      password: admin
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8888

#
#spring:
#  application:
#    name: cloud-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: file://${user.home}/Documents/cloud_config/configrepo
#  security:
#    user:
#      name: admin
#      password: admin
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#server:
#  port: 8888